FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN pip install --no-cache-dir aiobale python-dotenv requests

COPY main.py /app/main.py

CMD ["python", "main.py"]
